apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "zeus"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: eth-indexer-tls
      hosts:
        - api.zeus.fyi
  rules:
    - host: api.zeus.fyi
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: zeus
                port:
                  number: 80